flask_poc/user/views.py
# -*- coding: utf-8 -*-
"""User views."""
from flask import Blueprint, render_template
from flask_login import login_required

blueprint = Blueprint('user_blueprint', __name__, url_prefix='/users', static_folder='../static')


@blueprint.route('/')
@login_required
def members():
    """List members."""
    return render_template('users/members.html')

flask_poc/templates/401.html
{% extends "layout.html" %}

{% block page_title %}Unauthorized{% endblock %}

{% block content %}
<div class="jumbotron">
    <div class="text-center">
        <h1>401</h1>
        <p>You are not authorized to see this page. Please <a href="{{ url_for('public.home')}}">log in</a> or
            <a href="{{ url_for('public.register') }}">create a new account</a>.
        </p>
    </div>
</div>
{% endblock %}

flask_poc/templates/custom_list.html
{% extends 'admin/model/list.html' %}
{% block body %}
    <h1>Custom List View</h1>
    {{ super() }}
{% endblock %}

{% extends 'admin/model/list.html' %}
{% block list_row_actions %}
    {{ super() }}
  <form class="icon" method="POST" action="/admin/user/action/">
    <input id="action" name="action" value="approve" type="hidden">
    <input name="rowid" value="{{ get_pk_value(row) }}" type="hidden">
    <button onclick="return confirm('Are you sure you want to approve selected users?');" title="Approve">
      <span class="fa fa-ok glyphicon glyphicon-ok"></span>
    </button>
  </form>
{% endblock %}

flask_poc/templates/footer.html
<footer>
  <small>
  <ul class="company">
    <li>© Revenue Management Service</li>
  </ul>

    <ul class="footer-nav">

      <li><a href="{{ url_for('public.about') }}">About</a></li>

      <li><a href="mailto:optimus@treebohotels.com">Contact</a></li>
    </ul>
  </small>
</footer>

flask_poc/templates/layout.html
<!doctype html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
  <meta charset="utf-8">

  <title>{% block page_title %}
  
    Inventory Throttling Service
  
    {% endblock %}
  </title>
  <meta name="description" content="{% block meta_description %}{% endblock %}">
  <meta name="author" content="{% block meta_author %}{% endblock %}">

  <!-- Mobile viewport optimized: h5bp.com/viewport -->
  <meta name="viewport" content="width=device-width">

  {% block css %}{% endblock %}

</head>
<body class="{% block body_class %}{% endblock %}">
{% block body %}
{% with form=form  %}
{% include "nav.html" %}
{% endwith %}

<header>{% block header %}{% endblock %}</header>
<div class="{% block content_class %}container{% endblock content_class %}">

  <div role="main">
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    <div class="row">
      <div class="col-md-12">
        {% for category, message in messages %}
        <div class="alert alert-{{ category }}">
          <a class="close" title="Close" href="#" data-dismiss="alert">&times;</a>
         {{message}}
        </div><!-- end .alert -->
        {% endfor %}
      </div><!-- end col-md -->
    </div><!-- end row -->
        {% endif %}
    {% endwith %}

    {% block content %}{% endblock %}
  </div>

</div><!-- end container -->

{% include "footer.html" %}

<!-- JavaScript at the bottom for fast page loading -->
{% block js %}{% endblock %}
<!-- end scripts -->
{% endblock %}
</body>
</html>

flask_poc/templates/my_master.html
{% extends 'admin/base.html' %}

{% block access_control %}
{% if current_user.is_authenticated %}
<div class="btn-group pull-right">
    <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
        <i class="icon-user"></i> {{ current_user.login }} <span class="caret"></span>
    </a>
    <ul class="dropdown-menu">
        <li><a href="{{ url_for('admin.logout_view') }}">Log out</a></li>
    </ul>
</div>
{% endif %}
{% endblock %}

flask_poc/templates/nav.html
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">

  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="{{ url_for('public.home') }}">

      Inventory Throttling Service

    </a>
  </div>
  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav">
      <li><a href="{{ url_for('public.home') }}">Home</a></li>
      <li><a href="{{ url_for('public.about') }}">About</a></li>
    </ul>
    {% if current_user and current_user.is_authenticated %}
    <ul class="nav navbar-nav navbar-right">
        <li>
            <p class="navbar-text"><a class="navbar-link" href="{{ url_for('user_blueprint.members') }}">Logged in as {{ current_user.username }}</a></p>
        </li>
        <li><a class="navbar-link" href="{{ url_for('public.logout') }}"><i class="fa fa-sign-out"></i></a></li>

    </ul>
    {% elif form %}
    <ul class="nav navbar-nav navbar-right">
      <li><a href="{{ url_for('public.register') }}">Create account</a></li>
    </ul>
    <form id="loginForm" method="POST" class="navbar-form form-inline navbar-right" action="/" role="login">
      <div class="form-group">
        {{ form.username(placeholder="Username", class_="form-control") }}
        {{ form.password(placeholder="Password", class_="form-control") }}
      </div>
      <button type="submit" class="btn btn-default">Log in</button>
    </form>
    {% endif %}
  </div><!-- /.navbar-collapse -->
  </div><!-- /.container -->
</nav>